inventory:
  dotbox:
    primaryDisplay: DP-1
    displays:
      - displayName: BigFuckingDisplay
        name: DP-1
        description: Acer Technologies CG437K P 0x102199F9
        resolution: 3840x2160
        refreshRate: '120'
        position: '0x0'
        scale: 1
      - displayName: Dell S216DG
        name: DP-2
        description: 'Dell Inc. Dell S2716DG #ASNIq6m5JLvd'
        resolution: 2560x1440
        refreshRate: '120'
        position: -1440x-440
        scale: 1
        transform: 3
      - displayName: ThinkVision Touch
        name: DP-3
        description: Lenovo Group Limited M14t Gen2 V90F1P9D
        resolution: 2240x1400
        refreshRate: '60'
        position: 1120x2160
        scale: 1.25
  dotdeck:
    primaryDisplay: eDP-1
    displays:
      - displayName: SteamDeck
        name: SteamDeck
        resolution: 1280x800
        refreshRate: '60'
        position: '0x0'
        scale: 1
        virtual: true
      - displayName: SteamDeck LCD
        name: eDP-1
        resolution: 800x1280
        refreshRate: '60'
        position: '0x0'
        scale: 1
        mirror: SteamDeck
        transform: 3
  dotblackwall:
    primaryDisplay: eDP-1
    displays:
      - displayName: LegionGo
        name: eDP-1
        resolution: 1920x1200
        refreshRate: '120'
        position: '0x0'
        scale: 1.25
  dot-laptop:
    primaryDisplay: eDP-1
    displays:
      - displayName: Internal
        name: eDP-1
        resolution: 3840x2160
        refreshRate: '60'
        scale: 1
